### ISSUE TITLE
backrefmarker not replacing \\~

### ISSUE THREAD

**Issue by joereynolds** [KeyboardFire/vim-minisnip#14]
Hi,

Loving minisip by the way :D
However, there's one problem I've encountered that I can't seem to get around.

I have the following snippet (called _php_fnc)

```
function(${{+param+}})
{
    return {{+~\~1+}};
}
```

And when executed it does not insert anything into the backrefmarker.
For example if I type 'fnc<tab>test' I would expect the following to come back

```
function($test)
{
    return test;
}
```

But what actually comes back is

```
function($test)
{
    return {{+~\~1+}};
}
```

I have a feeling I've just got the syntax wrong, but I'm not sure. Any help would be appreciated!
Also, I would provide more examples for this in the documentation as it states that the key for backrefmarker is `\\~` whereas the example uses `~\~` which further confuses me haha!

Thanks for the help!

**Comment by manasthakur** [comment]
Hi @joereynolds,

You have to jump to the evaluation-marker in order to get the text. For example, after typing in the value of the `param`, you need to press `Tab` again.

I too was surprised a bit because the earlier snippet-engine I used (UltiSnips) used to update things on the fly; however, minisnip is lightweight and hence evaluates a backrefmarker once you jump to it.

**Comment by joereynolds** [comment]
@manasthakur 

I knew it would be something I was doing wrong.
Cheers!
